samples:
  SRR1106548:
    sequencer: miseq
    lc: truseq
  # mini:
  # hg38:
  # hg38_rna:
  # hg38_rna_mini:
  # atcc_even:
  # atcc_staggered:
  # viral_refseqc:
  UnAmbiguouslyMapped_ds.7:
    paired: False
  UnAmbiguouslyMapped_ds.buccal:
    paired: False
  UnAmbiguouslyMapped_ds.cityparks:
    paired: False
  UnAmbiguouslyMapped_ds.frankengenome:
    paired: False
  UnAmbiguouslyMapped_ds.frankengenome.mix:
    paired: False
  UnAmbiguouslyMapped_ds.gut:
    paired: False
  UnAmbiguouslyMapped_ds.hous1:
    paired: False
  UnAmbiguouslyMapped_ds.hous2:
    paired: False
  UnAmbiguouslyMapped_ds.nycsm:
    paired: False
  UnAmbiguouslyMapped_ds.soil:
    paired: False
  DNA1:
    sample: DNA1
    sequencer: miseq
    lc: nextera_xt
  DNA2:
    sample: DNA2
    sequencer: miseq
    lc: nextera_xt
  RNA1:
    sample: RNA1
    sequencer: miseq
    lc: nextera_xt
  RNA2:
    sample: RNA2
    sequencer: miseq
    lc: nextera_xt
  NTC:
    sample: NTC
    sequencer: miseq
    lc: nextera_xt
